name: CI/QA
on:
  pull_request:
    branches: [ ci, qa ]
jobs:
  debug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      BASE_BRANCH: ${{ github.base_ref }}
    steps:
      - run: echo "testing $BASE_BRANCH"

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      BASE_BRANCH: ${{ github.base_ref }}
    if: $BASE_BRANCH == 'qa' || $BASE_BRANCH == 'ci'
    steps:
      - run: echo "testing $BASE_BRANCH"
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Testing
        run: yarn test
      - name: Confirm integration
        if: ${{ success() }}
        run: yarn build
      - name: Approve pull request
        if: ${{ success() }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ $PR_NUMBER }}
      - name: Apply label
        if: ${{ failure() || cancelled() }}
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

