name: Stage PR for Master Release
on:
  push:
    branches: [ stage ]
jobs:
  PR:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
      - name: Rebase GIT
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git fetch --tags origin master
          git rebase origin/master
          git push -f "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" stage
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Setup PR Content
        run: |
          BODY=$(node -pe "require('child_process').execSync('yarn release --dry-run').toString().split('---')[1].replace(/%/g,'%25').replace(/\n/g,'%0A').trim()")
          TITLE=$(node -pe "require('child_process').execSync('yarn release --dry-run').toString().split('---')[1].trim().split('\n')[0]")
          echo "::set-env name=PR_TITLE::$TITLE"
          echo "::set-env name=PR_BODY::$BODY"
      - name: pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Production increment ${{ env.PR_TITLE }}
          pr_body: ${{ env.PR_BODY }}
          pr_draft: true
