name: Stage PR for Master Release
on:
  push:
    branches: [ stage ]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Setup PR Content
        run: |
          echo ::set-env name=PR_BODY::$(yarn release --dry-run)
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Production increment
          pr_body: ${{env.PR_BODY}}
          pr_draft: true

