name: Stage PR for Master Release
on:
  push:
    branches: [ stage ]
jobs:
  PR:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git fetch origin master
          git rebase origin/master
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Setup PR Content
        run: |
          BODY_TEST=$(node -pe "encodeURI(require('child_process').execSync('yarn release --dry-run').toString().split('---')[1].trim())")
          TITLE_TEST=$(node -pe "encodeURI(require('child_process').execSync('yarn release --dry-run').toString().split('---')[1].trim().split('\n')[0])")

          echo "$BODY_TEST"
          echo "$TITLE_TEST"
          echo "::set-env name=PR_TITLE::$TITLE_TEST"

          body="$(yarn release --dry-run)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "$body"

          echo "::set-env name=PR_BODY::$BODY_TEST"

      - name: pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Production increment v${{ env.PR_TITLE }}
          pr_body: "${{ env.PR_BODY }}"
          pr_draft: true
